server:
  port: 8081

spring.liquibase.enabled: true
spring.liquibase.change-log: classpath:db/db.changelog-master.yaml
spring.liquibase.contexts: dev
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show_sql: true
spring.datasource:
     url: 'jdbc:oracle:thin:52f474e93332@:1521/ORCLPDB1'
     username: INFRA
     password: momS51tsmu
     driver-class-oracle:
      jdbc:
       driver: oracle.jdbc.OracleDriver