server:
  port: 8082
spring.jpa.hibernate.ddl-auto: update
spring.jpa.hibernate.show_sql: true
spring.datasource:
     url: 'jdbc:oracle:thin:@172.17.0.2:1521/ORCLPDB1'
     username: INFRA
     password: momS51tsmu
     driver-class-oracle:
      jdbc:
       driver: oracle.jdbc.OracleDriver